import { useEffect, useState } from "react";
import { Activity, Clock3, Database, Globe2, KeyRound, Network, RefreshCw, ShieldAlert, ShieldCheck } from "lucide-react";

function formatTime(timestamp) { try { return new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(timestamp)); } catch { return timestamp; } }
function moduleIcon(module) { if (module === "Web Security") return Globe2; if (module === "Network Security") return Network; if (module === "Password Security" || module === "Crypto Lab") return KeyRound; return ShieldAlert; }
function text(value) { return String(value || "—"); }

function WebPreview({ result }) {
  const summary = result.report_summary || {}; const recon = result.recon || {}; const headers = result.security_headers || []; const ports = result.ports || []; const technologies = result.technology || [];
  return <div className="saved-preview"><div className="result-metrics"><Metric label="Findings" value={summary.total ?? 0} /><Metric label="Open ports" value={ports.length} /><Metric label="Headers to review" value={headers.length} /><Metric label="Technology" value={technologies.length} /></div><div className="result-detail-grid"><ResultBlock title="Target overview"><span>Host: <b>{text(recon.hostname)}</b></span><span>Response: <b>{text(recon.status_code)}</b></span><span>Server: <b>{text(recon.server)}</b></span></ResultBlock><ResultBlock title="Review items">{headers.length ? headers.slice(0, 4).map((item) => <span key={item.header}><b>{item.header}</b> · {item.description}</span>) : <span>No missing security headers were recorded.</span>}</ResultBlock><ResultBlock title="Detected services">{ports.length ? ports.slice(0, 5).map((item) => <span key={item.port}><b>{item.port}/TCP</b> · {item.service}</span>) : <span>No open ports recorded.</span>}</ResultBlock><ResultBlock title="Technology">{technologies.length ? technologies.slice(0, 4).map((item, index) => <span key={`${item.name}-${index}`}><b>{item.name}</b> · {item.type}</span>) : <span>No technology indicators recorded.</span>}</ResultBlock></div></div>;
}
function PasswordPreview({ result }) { const checks = result.checks || {}; return <div className="saved-preview"><div className="password-result"><div className={`password-rating ${String(result.rating || "").toLowerCase().replaceAll(" ", "-")}`}><strong>{text(result.rating)}</strong><span>{result.score ?? 0} / {result.maximum_score ?? 10}</span></div><div className="check-list"><span>Length: <b>{text(checks.length)}</b></span><span>Uppercase: <b>{checks.uppercase ? "Included" : "Missing"}</b></span><span>Numbers: <b>{checks.numbers ? "Included" : "Missing"}</b></span><span>Special characters: <b>{checks.special_character ? "Included" : "Missing"}</b></span></div></div><ResultBlock title="Recommended next steps">{(result.suggestions || []).map((item) => <span key={item}>{item}</span>)}</ResultBlock></div>; }
function NetworkPreview({ result }) { const services = result.open_services || result.open_ports || []; return <div className="saved-preview"><div className="result-metrics"><Metric label="Open ports" value={result.total_open_ports ?? services.length} /><Metric label="Resolved IP" value={result.resolution?.ip_address || result.ip_address || "—"} /><Metric label="Host status" value={result.host_check?.status || result.host_status || "Checked"} /></div><ResultBlock title="Open services">{services.length ? services.slice(0, 8).map((item, index) => <span key={`${item.port}-${index}`}><b>Port {item.port}</b> · {item.service || item.state || "Open"}</span>) : <span>No open services were found.</span>}</ResultBlock></div>; }
function GenericPreview({ item }) { const result = item.output || {}; if (item.module === "Phishing Analyzer") return <div className="saved-preview"><div className="result-metrics"><Metric label="Risk level" value={result.risk_level || result.risk || "Analysed"} /><Metric label="Risk score" value={result.risk_score ?? result.score ?? "—"} /></div><ResultBlock title="Inspection summary">{(result.reasons || result.findings || ["Passive URL inspection completed."]).slice(0, 5).map((value, index) => <span key={index}>{typeof value === "string" ? value : value.description || value.title || "Inspection item recorded."}</span>)}</ResultBlock></div>; if (item.module === "Crypto Lab") return <div className="saved-preview"><ResultBlock title="Completed operation"><span><b>{String(result.operation || "Operation").replaceAll("_", " ")}</b> completed successfully.</span><span>For privacy, source text is not stored in history.</span></ResultBlock></div>; return <div className="saved-preview"><ResultBlock title="Completed result"><span>The result was saved locally. Open the relevant module to run it again.</span></ResultBlock></div>; }
function ResultPreview({ item }) { if (item.module === "Web Security") return <WebPreview result={item.output} />; if (item.module === "Password Security") return <PasswordPreview result={item.output} />; if (item.module === "Network Security") return <NetworkPreview result={item.output} />; return <GenericPreview item={item} />; }
function Metric({ label, value }) { return <div><small>{label}</small><strong>{text(value)}</strong></div>; }
function ResultBlock({ title, children }) { return <div className="result-block"><strong>{title}</strong><div>{children}</div></div>; }

export default function Reports() {
  const [history, setHistory] = useState([]); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [expanded, setExpanded] = useState(null);
  async function load() { setLoading(true); setError(""); try { const response = await fetch("/api/history"); const data = await response.json(); if (!response.ok || !data.success) throw new Error(data.error || "Unable to load activity history."); setHistory(data.history || []); } catch (requestError) { setError(requestError.message); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  return <section className="tool-page history-page"><div className="module-header"><div><p className="eyebrow">NIGHT HUNTER · LOCAL AUDIT TRAIL</p><h2>Activity History</h2><p className="subtitle">Completed module actions and their results are saved automatically on this computer.</p></div><button className="secondary-action" onClick={load} disabled={loading}><RefreshCw size={16} />REFRESH</button></div>{error && <p className="tool-error">{error}</p>}<div className="history-privacy"><ShieldCheck size={18} /><span>History uses the same friendly result format as the modules. Passwords and Crypto Lab source text are never included.</span></div><div className="history-list">{history.length ? history.map((item) => { const Icon = moduleIcon(item.module); const open = expanded === item.id; return <article className="history-item" key={item.id}><div className="history-icon"><Icon size={19} /></div><div className="history-body"><div className="history-title"><strong>{item.module}</strong><span className="history-status">{item.status}</span></div><p>{item.summary}</p><div className="history-meta"><span>{item.target}</span><span><Clock3 size={13} />{formatTime(item.timestamp)}</span></div>{item.output && Object.keys(item.output).length > 0 && <button className="history-toggle" type="button" onClick={() => setExpanded(open ? null : item.id)}><Activity size={15} />{open ? "HIDE RESULT" : "VIEW RESULT"}</button>}{open && <ResultPreview item={item} />}</div></article>; }) : <div className="empty-findings"><Database size={24} /><div><strong>{loading ? "Loading local history..." : "No activity saved yet"}</strong><p>Run a module and its completed result will appear here automatically.</p></div></div>}</div></section>;
}
